---
codecov:
  require_ci_to_pass: true
rgy
ignore:
  - testsuite/*
  - x/*
bio
coverage:
  # range for color spectrum display, red=50%, green=80%
  range: "50...80"
  round: down
  precision: 1
bhy
  status:
    project: true
    patch: true
    changes: false
